on:
  push:
    paths:
      - tensorflow/**/*
    branches:
      - "master"
      - "main"
      - "latest"
jobs:
  build-tensorflow:
    strategy:
      matrix:
        include:
          - context: tensorflow
            dockerfile: tensorflow/Dockerfile
            name: tensorflow-env
          - context: tensorflow
            dockerfile: tensorflow/Dockerfile.builder
            name: tensorflow-builder
    uses: ./.github/workflows/build.yml
    with:
      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.dockerfile }}
      name: ${{ matrix.name }}
