on:
  push:
    paths:
      - tensorflow
jobs:
  build-tensorflow:
    strategy:
      - context: tensorflow
        dockerfile: Dockerfile
        name: tensorflow-env
      - context: tensorflow
        dockerfile: Dockerfile.builder
        name: tensorflow-builder
    uses: ./.github/workflows/build.yml
    with:
      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.dockerfile }}
      name: ${{ matrix.name }}
